# Generated by Django 6.0.5 on 2026-05-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchschedule',
            name='commitment_type',
            field=models.CharField(choices=[('Reunião', 'Reuniao'), ('Visita', 'Visita'), ('Apresentação', 'Apresentacao'), ('Culto Parceiro', 'Culto Parceiro'), ('Ação Evangelística', 'Acao Evangelistica')], max_length=30),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(choices=[('Administrativa', 'Administrativa'), ('Ordinária', 'Ordinaria'), ('Extraordinária', 'Extraordinaria'), ('Culto', 'Culto'), ('Oração', 'Oracao')], max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='classification',
            field=models.CharField(choices=[('Gideão', 'Gideao'), ('Auxiliar', 'Auxiliar')], max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='official_role',
            field=models.CharField(choices=[('Presidente', 'Presidente'), ('Vice-presidente', 'Vice Presidente'), ('Capelão', 'Capelao'), ('Secretário', 'Secretario'), ('Tesoureiro', 'Tesoureiro'), ('Nenhum', 'Nenhum')], default='Nenhum', max_length=30),
        ),
        migrations.AlterField(
            model_name='minutes',
            name='status',
            field=models.CharField(choices=[('Rascunho', 'Rascunho'), ('Revisão', 'Revisao'), ('Aprovada', 'Aprovada'), ('Arquivada', 'Arquivada')], default='Rascunho', max_length=20),
        ),
    ]
