# Generated by Django 6.0.3 on 2026-05-18 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ata', '0002_alter_churchschedule_commitment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GideonFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('neighborhood', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('donation_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('became_friend_date', models.DateField(verbose_name='Data de se tornar Amigo do Gideão')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo'), ('Pendente', 'Pendente')], default='Ativo', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('contacted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gideon_friends_contacted', to='ata.member', verbose_name='Gideão/Auxiliar responsável')),
            ],
            options={
                'verbose_name': 'Amigo do Gideão',
                'verbose_name_plural': 'Amigos do Gideão',
                'ordering': ['full_name'],
            },
        ),
    ]
